-- INSERT INTO department_id (id)
-- VALUES (1),
--        (2),
--        (3),
--        (4),

-- INSERT INTO departments (departments)
-- VALUES ("Engineering", true, 1),
--        ("Finance", true, 2),
--        ("Legal", true, 3),
--        ("Sales", true, 4),